---
apiVersion: v1
kind: Namespace
metadata:
  name: minio-tenant-goepp

---
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  annotations:
    prometheus.io/path: /minio/v2/metrics/cluster
    prometheus.io/port: "9000"
    prometheus.io/scrape: "true"
  labels:
    app: minio
  name: minio-goepp
  namespace: minio-tenant-goepp
spec:
  certConfig: {}
  configuration:
    name: storage-configuration
  env: []
  externalCaCertSecret: []
  externalCertSecret: []
  externalClientCertSecrets: []
  features:
    bucketDNS: false
    domains: {}
  image: quay.io/minio/minio:RELEASE.2025-04-08T15-41-24Z
  imagePullSecret: {}
  mountPath: /export
  podManagementPolicy: Parallel
  pools:
  - affinity:
      nodeAffinity: {}
      podAffinity: {}
      podAntiAffinity: {}
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
      seccompProfile:
        type: RuntimeDefault
    name: pool-0
    nodeSelector: {}
    resources: {}
    securityContext:
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
    servers: 4
    tolerations: []
    topologySpreadConstraints: []
    volumeClaimTemplate:
      apiVersion: v1
      kind: persistentvolumeclaims
      metadata: {}
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: local-path
      status: {}
    volumesPerServer: 2
  priorityClassName: ""
  requestAutoCert: true
  serviceAccountName: ""
  serviceMetadata:
    consoleServiceAnnotations: {}
    consoleServiceLabels: {}
    minioServiceAnnotations: {}
    minioServiceLabels: {}
  subPath: ""
  users:
  - name: cnpg-backup

---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: minio-console-insecure-transport
  namespace: minio-tenant-goepp
spec:
  insecureSkipVerify: true

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: minio-console-ingress
  namespace: minio-tenant-goepp
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`minio-prod.goepp.net`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: minio-goepp-console
          port: 9443
          serversTransport: minio-console-insecure-transport

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: minio-s3-ingress
  namespace: minio-tenant-goepp
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`minio-s3-prod.goepp.net`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: minio
          port: 443
          serversTransport: minio-console-insecure-transport

