---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-mcp
  namespace: grafana
  labels:
    app: grafana-mcp
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: grafana-mcp
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: grafana-mcp
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      containers:
      - name: grafana-mcp
        image: grafana/mcp-grafana:0.17.2
        imagePullPolicy: IfNotPresent
        args:
          - "-t"
          - "streamable-http"
          - "--address"
          - "0.0.0.0:8000"
          - "--allowed-hosts"
          - "grafana-mcp-prod.goepp.net"
        env:
          - name: GRAFANA_URL
            value: "http://grafana.grafana.svc.cluster.local.:3000"
          - name: GRAFANA_ORG_ID
            value: "1"
        envFrom:
          - secretRef:
              name: grafana-mcp-secrets
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        ports:
        - name: http
          containerPort: 8000
        readinessProbe:
          tcpSocket:
            port: 8000
        livenessProbe:
          tcpSocket:
            port: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: grafana-mcp
  namespace: grafana
spec:
  selector:
    app: grafana-mcp
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-mcp-ingress
  namespace: grafana
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`grafana-mcp-prod.goepp.net`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: grafana-mcp
          port: 8000
