---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cloudflare
  namespace: kopia
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: dan@goepp.com
    privateKeySecretRef:
      name: cloudflare-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare
              key: api-token

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-kopia-goepp-net
  namespace: kopia
spec:
  secretName: wildcard-kopia-goepp-net-tls
  dnsNames:
    - "goepp.net"
    - "*.goepp.net"
  issuerRef:
    name: cloudflare
    kind: Issuer