---
apiVersion: v1
kind: Namespace
metadata:
  name: victoriametrics

---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: vms-prod
  namespace: victoriametrics
spec:
  image:
    repository: victoriametrics/victoria-metrics
    tag: v1.148.0
    pullPolicy: IfNotPresent
  storageDataPath: /data
  volumes:
    - name: data
      hostPath:
        path: /mnt/k3s-prod-data/vms-prod
  retentionPeriod: "30d"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - k3s-prod-11
                  - k3s-prod-12
                  - k3s-prod-13
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 1024Mi

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vms-prod-ingress
  namespace: victoriametrics
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`vms-prod.goepp.net`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: vmsingle-vms-prod
          port: 8429

