---
apiVersion: v1
kind: ConfigMap
metadata:
  name: graylog-config
  namespace: graylog
data:
  graylog.conf: |
    ############################
    # GRAYLOG CONFIGURATION FILE
    ############################

    is_master = false
    node_id_file = /usr/share/graylog/data/node-id
    password_secret = ${GRAYLOG_PASSWORD_SECRET}

    # The default root user is named 'admin'
    #root_username = admin

    # Create one by using for example: echo -n yourpassword | shasum -a 256
    root_password_sha2 = ${GRAYLOG_ROOT_PASSWORD_SHA2}

    # The email address of the root user.
    # Default is empty
    #root_email = ""

    # The time zone setting of the root user. See http://www.joda.org/joda-time/timezones.html for a list of valid time zones.
    root_timezone = America/New_York

    bin_dir = /usr/share/graylog/bin
    data_dir = /usr/share/graylog/data
    plugin_dir = /usr/share/graylog/plugin

    ###############
    # HTTP settings
    ###############

    http_bind_address = 0.0.0.0:9000

    #### HTTP publish URI
    # Default: http://$http_bind_address/
    # http_publish_uri = https://graylog-prod.goepp.net/
    # DON'T SET THIS, if you do the nodes will try to communicate via this address!

    #### External Graylog URI
    http_external_uri = https://graylog-prod.goepp.net/

    #### Enable CORS headers for HTTP interface
    http_enable_cors = true

    # Comma separated list of trusted proxies that are allowed to set the client address with X-Forwarded-For
    # header. May be subnets, or hosts.
    trusted_proxies = 10.43.0.0/8

    elasticsearch_hosts = ${GRAYLOG_ELASTICSEARCH_HOSTS}
    rotation_strategy = count
    elasticsearch_max_docs_per_index = 20000000
    elasticsearch_max_number_of_indices = 20
    retention_strategy = delete
    elasticsearch_shards = 4
    elasticsearch_replicas = 0
    elasticsearch_index_prefix = graylog

    # Do you want to allow searches with leading wildcards? This can be extremely resource hungry and should only
    # be enabled with care. See also: https://docs.graylog.org/docs/query-language
    allow_leading_wildcard_searches = false

    # Do you want to allow searches to be highlighted? Depending on the size of your messages this can be memory hungry and
    # should only be enabled after making sure your Elasticsearch cluster has enough memory.
    allow_highlighting = false

    # Analyzer (tokenizer) to use for message and full_message field. The "standard" filter usually is a good idea.
    # All supported analyzers are: standard, simple, whitespace, stop, keyword, pattern, language, snowball, custom
    # Elasticsearch documentation: https://www.elastic.co/guide/en/elasticsearch/reference/2.3/analysis.html
    # Note that this setting only takes effect on newly created indices.
    #
    # ATTENTION: These settings have been moved to the database in Graylog 2.2.0. When you upgrade, make sure to set these
    #            to your previous settings so they will be migrated to the database!
    #            This configuration setting is only used on the first start of Graylog. After that,
    #            index related settings can be changed in the Graylog web interface on the 'System / Indices' page.
    #            Also see https://docs.graylog.org/docs/index-model#index-set-configuration
    elasticsearch_analyzer = standard

    output_batch_size = 500
    output_flush_interval = 1
    output_fault_count_threshold = 5
    output_fault_penalty_seconds = 30
    processbuffer_processors = 5
    outputbuffer_processors = 3

    processor_wait_strategy = blocking
    ring_size = 65536

    inputbuffer_ring_size = 65536
    inputbuffer_processors = 2
    inputbuffer_wait_strategy = blocking

    message_journal_enabled = true
    message_journal_dir = data/journal

    lb_recognition_period_seconds = 3

    mongodb_uri = ${GRAYLOG_MONGODB_URI}
    mongodb_max_connections = 1000
    mongodb_threads_allowed_to_block_multiplier = 5

    # Email transport
    transport_email_enabled = true
    transport_email_hostname = mail.goepp.net.
    transport_email_port = 587
    transport_email_use_auth = false
    transport_email_subject_prefix = [graylog]
    transport_email_from_email = graylog@goepp.net
    transport_email_use_tls = false
    transport_email_use_ssl = false
    transport_email_web_interface_url = https://graylog-prod.goepp.net/

    proxied_requests_thread_pool_size = 32

  log4j2.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <Configuration packages="org.graylog2.log4j" shutdownHook="disable">
        <Appenders>
            <Console name="STDOUT" target="SYSTEM_OUT">
                <PatternLayout pattern="%d %-5p: %c - %m%n"/>
            </Console>

            <!-- Internal Graylog log appender. Please do not disable. This makes internal log messages available via REST calls. -->
            <Memory name="graylog-internal-logs" bufferSizeBytes="20MB">
                <PatternLayout pattern="%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-5p [%c{1}] %m%n"/>
            </Memory>
        </Appenders>
        <Loggers>
            <!-- Application Loggers -->
            <Logger name="org.graylog2" level="info"/>
            <Logger name="com.github.joschi.jadconfig" level="warn"/>
            <!-- Prevent DEBUG message about Lucene Expressions not found. -->
            <Logger name="org.elasticsearch.script" level="warn"/>
            <!-- Disable messages from the version check -->
            <Logger name="org.graylog2.periodical.VersionCheckThread" level="off"/>
            <!-- Silence chatty natty -->
            <Logger name="com.joestelmach.natty.Parser" level="warn"/>
            <!-- Silence Kafka log chatter -->
            <Logger name="org.graylog.shaded.kafka09.log.Log" level="warn"/>
            <Logger name="org.graylog.shaded.kafka09.log.OffsetIndex" level="warn"/>
            <Logger name="org.apache.kafka.clients.consumer.ConsumerConfig" level="warn"/>
            <!-- Silence useless session validation messages -->
            <Logger name="org.apache.shiro.session.mgt.AbstractValidatingSessionManager" level="warn"/>
            <!-- Silence Azure SDK messages -->
            <Logger name="com.azure" level="warn"/>
            <Logger name="reactor.core.publisher.Operators" level="off"/>
            <Logger name="com.azure.messaging.eventhubs.PartitionPumpManager" level="off"/>
            <Logger name="com.azure.core.amqp.implementation.ReactorReceiver" level="off"/>
            <Logger name="com.azure.core.amqp.implementation.ReactorDispatcher" level="off"/>
            <!-- Silence Apache Hadoop/Avro log chatter -->
            <Logger name="org.apache.hadoop" level="warn"/>
            <Logger name="org.apache.parquet.hadoop.InternalParquetRecordReader" level="warn"/>
            <Logger name="org.apache.avro.Schema" level="error"/>
            <Root level="warn">
                <AppenderRef ref="STDOUT"/>
                <AppenderRef ref="graylog-internal-logs"/>
            </Root>
        </Loggers>
    </Configuration>
