---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: awx-backup-pv
  namespace: awx
spec:
  storageClassName: local-path
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/backups/awx"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: awx-backup-pvc
  namespace: awx
spec:
  storageClassName: local-path
  volumeName: awx-backup-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
