---
apiVersion: v1
kind: Namespace
metadata:
  name: management

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: propane-sync
  namespace: management
spec:
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: propane-sync
            image: danielgoepp/propane-sync:latest
            imagePullPolicy: Always
          restartPolicy: Never
