---
apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: homeassistant-prod-manual
  namespace: cnpg-homeassistant
spec:
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
  cluster:
    name: homeassistant-prod