---
apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: grafana-prod-manual
  namespace: cnpg-grafana
spec:
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
  cluster:
    name: grafana-prod