---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: minio-backup
  namespace: cnpg-grafana
spec:
  retentionPolicy: "1d"
  configuration:
    destinationPath: s3://cnpgbackup/
    endpointURL: https://minio-s3-prod.goepp.net
    s3Credentials:
      accessKeyId:
        name: minio-creds
        key: MINIO_ACCESS_KEY
      secretAccessKey:
        name: minio-creds
        key: MINIO_SECRET_KEY

---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: grafana-prod
  namespace: cnpg-grafana
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:18.3-standard-trixie
  instances: 2

  storage:
    size: 1Gi

  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "500m"

  postgresql:
    parameters:
      timezone: "America/New_York"

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - k3s-prod-11
                  - k3s-prod-12
                  - k3s-prod-13

  bootstrap:
    initdb:
      database: grafana
      owner: grafana

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      parameters:
        barmanObjectName: minio-backup
        isWALArchiver: "true"

---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: grafana-prod-backup
  namespace: cnpg-grafana
spec:
  schedule: "0 0 0 * * *"
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
  immediate: true
  cluster:
    name: grafana-prod

---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: cnpg-prod-monitor
  namespace: cnpg-grafana
spec:
  podMetricsEndpoints:
    - port: metrics
  selector:
    matchLabels:
      "cnpg.io/cluster": grafana-prod
