---
apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: doholm-prod-manual
  namespace: cnpg-doholm
spec:
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
  cluster:
    name: doholm-prod