image:
  repository: quay.io/prometheus/alertmanager
  pullPolicy: IfNotPresent
  tag: "v0.32.1"

extraArgs:
  web.external-url: "https://alertmanager-prod.goepp.net"

extraSecretMounts:
  - name: alertmanager-secrets
    mountPath: /etc/alertmanager/secrets
    secretName: alertmanager-secrets
    readOnly: true

livenessProbe:
  httpGet:
    path: /
    port: http

readinessProbe:
  httpGet:
    path: /
    port: http

ingress:
  enabled: true
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  hosts:
    - host: alertmanager-prod.goepp.net
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

persistence:
  enabled: false
  accessModes:
    - ReadWriteOnce
  size: 50Mi

config:
  enabled: true
  global: 
    smtp_smarthost: 'mail.goepp.net.:587'
    smtp_from: 'woodpeckergoepp@gmail.com'
    smtp_hello: 'alertmanager.goepp.net'
    smtp_require_tls: false
    resolve_timeout: 5m

  templates:
    - '/etc/alertmanager/*.tmpl'

  receivers:
    - name: 'team-goepp-mails'
      email_configs:
        - to: 'dan@goepp.com'
          send_resolved: true

    - name: 'zigbee-offline-mails'
      email_configs:
        - to: 'dan@goepp.com'
          send_resolved: true
          headers:
            Subject: '{{ template "custom.subject" . }}'

    - name: 'co2-alert-mails'
      email_configs:
        - to: 'dan@goepp.com'
          send_resolved: true
          headers:
            Subject: '{{ template "co2.subject" . }}'

    - name: awx-webhook-reboot-mudderpi
      webhook_configs:
        - url: "https://awx-prod.goepp.net/api/v2/job_templates/43/launch/"
          http_config:
            authorization:
              type: Bearer
              credentials_file: /etc/alertmanager/secrets/awx-token
          send_resolved: false

  route:
    receiver: 'team-goepp-mails'
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    group_by: [alertname, severity, instance]

    routes:
      - matchers:
          - alertname="Zigbee - Device Offline"
        group_by: ["alertname"]
        receiver: zigbee-offline-mails
        repeat_interval: 4h

      - matchers:
          - alertname=~".*CO2.*"
        group_by: ["alertname"]
        receiver: co2-alert-mails
        repeat_interval: 4h

      - matchers:
          - alertname="UPS Input Voltage - Data Collection Per Location"
          - location="Leyden"
        group_by: ["alertname", "location"]
        receiver: awx-webhook-reboot-mudderpi
        repeat_interval: 24h

templates:
  custom.tmpl: |-
    {{ define "__subject" -}}
    [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .GroupLabels.SortedPairs.Values | join " " }}
    {{- end }}

    {{ define "custom.subject" -}}
    [{{ .Status | toUpper }}:{{ if eq .Status "firing" }}{{ .Alerts.Firing | len }}{{ else }}{{ .Alerts.Resolved | len }}{{ end }}] {{ .GroupLabels.alertname }}{{ range .Alerts }}{{ if .Labels.device }} - {{ .Labels.device }}{{ end }}{{ end }}
    {{- end }}

    {{ define "co2.subject" -}}
    [{{ .Status | toUpper }}:{{ if eq .Status "firing" }}{{ .Alerts.Firing | len }}{{ else }}{{ .Alerts.Resolved | len }}{{ end }}] {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}
    {{- end }}